name: build-release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - name: linux-aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            needs_cross: true
          - name: macos-x86_64
            os: macos-13
            target: x86_64-apple-darwin
          - name: macos-aarch64
            os: macos-14
            target: aarch64-apple-darwin

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross toolchain
        if: ${{ matrix.needs_cross == true }}
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y gcc-aarch64-linux-gnu

      - name: Configure cross linker
        if: ${{ matrix.target == 'aarch64-unknown-linux-gnu' }}
        run: |
          echo "CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc" >> "$GITHUB_ENV"
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> "$GITHUB_ENV"

      - name: Build
        working-directory: crossfetch
        run: |
          cargo build --locked --release --target ${{ matrix.target }}

      - name: Package artifact
        working-directory: crossfetch
        run: |
          binary_path="target/${{ matrix.target }}/release/crossfetch"
          package_name="crossfetch-${{ matrix.name }}"
          mkdir -p dist
          cp "$binary_path" "dist/crossfetch"
          tar -C dist -czf "dist/${package_name}.tar.gz" crossfetch
          rm dist/crossfetch
        shell: bash

      - name: Upload artifact to workflow run
        uses: actions/upload-artifact@v4
        with:
          name: crossfetch-${{ matrix.name }}
          path: crossfetch/dist/*.tar.gz

      - name: Upload to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: crossfetch/dist/*
